version: "2.4"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ms_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  users:
    build:
      context: .
      dockerfile: ./services/users-service/Dockerfile
    container_name: ms_users
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      EXCHANGE: app.topic
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    ports:
      - "3001:3001"

  orders:
    build:
      context: .
      dockerfile: ./services/orders-service/Dockerfile
    container_name: ms_orders
    environment:
      PORT: 3002
      USERS_BASE_URL: http://users:3001
      HTTP_TIMEOUT_MS: 2000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      EXCHANGE: app.topic
      QUEUE: orders.q
      ROUTING_KEY_USER_CREATED: user.created
    depends_on:
      rabbitmq:
        condition: service_healthy
      users:
        condition: service_started
    restart: always
    ports:
      - "3002:3002"

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: ms_gateway
    environment:
      PORT: 3000
      USERS_URL: http://ms_users:3001
      ORDERS_URL: http://ms_orders:3002
    depends_on:
      users:
        condition: service_started
      orders:
        condition: service_started
    restart: always
    ports:
      - "3000:3000"

